language: node_js
node_js:
  - "10.5"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change